version: '2'
services:
    transmart_dev_rserver:
        container_name: transmart_dev_rserver
        image: transmart_rserver
        volumes:
            - transmart_dev_tomcat_webapps:/usr/local/tomcat/webapps # Used for sharing R scripts
            - transmart_dev_var_tmp_jobs:/var/tmp/jobs # Used for sharing R results
            - transmart_dev_tmp:/tmp # Used for sharing R results
            - /var/centrifydc/:/var/centrifydc
            - /var/centrify:/var/centrify
            - /etc/pam.d:/etc/pam.d.host:ro
            - /etc/nsswitch.conf:/etc/nsswitch.conf:ro
            - /etc/centrifydc:/etc/centrifydc:ro
            - /etc/krb5.conf:/etc/krb5.conf:ro
            - /etc/krb5.keytab:/etc/krb5.keytab:ro
            - /etc/krb5.ccache:/etc/krb5.ccache:ro
            - /sys/fs/cgroup:/sys/fs/cgroup:ro # To use D-Bus http://serverfault.com/a/825027/93281
#            - /var/local/rstudio/home:/home
            - /home:/home
            - /run # To use D-Bus thanks to https://forums.docker.com/t/any-simple-and-safe-way-to-start-services-on-centos7-systemd/5695/8
#            - /tmp # To use D-Bus thanks to https://forums.docker.com/t/any-simple-and-safe-way-to-start-services-on-centos7-systemd/5695/8
        environment:
            - http_proxy=${http_proxy_IN_CONTAINER}
            - HTTP_PROXY=${HTTP_PROXY_IN_CONTAINER}
            - https_proxy=${https_proxy_IN_CONTAINER}
            - HTTPS_PROXY=${HTTPS_PROXY_IN_CONTAINER}
        ports:
            - "6313:6311" # Rserve
            - "8789:8787" # RStudio
        hostname: ${HOSTNAME}
        tty: true
        stdin_open: true
#        cap_add:
#            - SYS_PTRACE # To use reredirect https://github.com/jerome-pouiller/reredirect/issues/5#issuecomment-282320757
#            - SYS_ADMIN # To use D-Bus http://serverfault.com/a/825027/93281
#        security_opt:
#            - seccomp:unconfined # To use D-Bus thanks to https://forums.docker.com/t/any-simple-and-safe-way-to-start-services-on-centos7-systemd/5695/9
    transmart_dev_servers:
        container_name: transmart_dev_servers
        build:
            context: ../servers
            args:
                - http_proxy=${http_proxy_IN_CONTAINER}
                - HTTP_PROXY=${HTTP_PROXY_IN_CONTAINER}
                - https_proxy=${https_proxy_IN_CONTAINER}
                - HTTPS_PROXY=${HTTPS_PROXY_IN_CONTAINER}
#        depends_on:
#            - transmart_dev_rserver
        links:
            - transmart_dev_rserver
        ports:
            - "8002:8000"
            - "8082:8080"
            - "8985:8983"
            - "1101:1101"
            - "1201:1201"
            - "1301:1301"
            - "1100:1100"
        volumes:
            - /var/local/transmart/dev/.grails:/root/.grails
#            - /transmart_dev:/transmart_dev
            - /var/local/transmart/dev/data/solr:/usr/local/transmart/transmart-data-sanofi-release-16.1/solr/solr
            - /var/local/transmart/dev/etc/solr-auth:/usr/local/transmart/transmart-data-sanofi-release-16.1/solr/etc/auth
            - /var/local/transmart/dev/workspace:/workspace
            - /var/local/transmart/.m2/repository:/root/.m2/repository
            - /var/local/transmart/etc:/usr/local/etc
            - /etc:/etc.host:ro
            - transmart_dev_tomcat_webapps:/usr/local/tomcat/webapps # Used for sharing R scripts
            - transmart_dev_var_tmp_jobs:/var/tmp/jobs # Used for sharing R results
            - transmart_dev_tmp:/tmp # Used for sharing R results
        environment:
            - http_proxy=${http_proxy_IN_CONTAINER}
            - HTTP_PROXY=${HTTP_PROXY_IN_CONTAINER}
            - https_proxy=${https_proxy_IN_CONTAINER}
            - HTTPS_PROXY=${HTTPS_PROXY_IN_CONTAINER}
            - DEBUG_WITH_JPDA=true
            - DEBUG_WITH_EJSTATD=true
            - DEBUG_WITH_JMX=true
            - HOST_HOSTNAME=${HOSTNAME}
            - EJSTATD_RPORT=1101
            - EJSTATD_HPORT=1201
            - EJSTATD_VPORT=1301
            - JMXREMOTE_PORT=1100
            - BRANCH=sanofi-release-16.1-dev
    transmart_dev_front:
        container_name: transmart_dev_front
        build:
            context: ../front
            args:
                - http_proxy=${http_proxy_IN_CONTAINER}
        ports:
            - "82:80"
            - "445:443"
        links:
            - transmart_dev_servers:transmart_app
        volumes:
            - /var/local/transmart/dev/etc/front-certs:/usr/local/apache2/conf/certs
            - /var/local/transmart/dev/etc/solr-auth:/usr/local/apache2/conf/solr-auth
        environment:
            - HOST_HOSTNAME=${HOSTNAME}
volumes:
    transmart_dev_tomcat_webapps:
    transmart_dev_var_tmp_jobs:
    transmart_dev_tmp: